/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm")             // ← version を書かない
}

dependencies {
    api(project(":list"))
}
