/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm")             // ← version を書かない
}
dependencies {
    implementation(kotlin("stdlib"))      // 本番コード用
    testImplementation(kotlin("test"))    // Kotlin 標準テスト
    // 👉 JUnit5 を追加
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.2")
}

tasks.test {
    useJUnitPlatform()  // ← JUnit5 を使うよ宣言
}