spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simdb?serverTimezone=Asia/Tokyo&useSSL=false&allowPublicKeyRetrieval=true
    username: simuser
    password: simpass
  jpa:
    hibernate:
      ddl-auto: validate   # Flyway で作ったテーブルと一致するか検証
    show-sql: true

  flyway:
    # classpath: は Boot のデフォルトなので書かなくても良い
    # locations: classpath:db/migration
    enabled: true
